### ISSUE TITLE
The mod doesn't work 1.19

### ISSUE THREAD

**Issue by BluEagle-Dev** [Just-Ju/Inmis-Back-Pack-Mod-Retextured#1]
I am playing on 1.19 and i am using the 1.19 version of the mod but it doesn't change the backpack models.. That's a bummer because they look way better

**Comment by Just-Ju** [comment]
I will take a look at this later but it should be working did you make sure you downloaded the retexrured version and not the version from curseforge?

**Comment by Just-Ju** [comment]
can confirm this is working fine with 1.19

**Comment by BluEagle-Dev** [comment]
I just realized this is a replacement mod, not just a retexture. My bad, i thought it went along side the base mod. Can you transform it into a texture pack tho?

**Comment by Just-Ju** [comment]
hey sorry for the late reply no i dont want to create it as a texture pack having it as a replacement mod just mean you can save on data loading just 1 mod and not 1 mod and a texture pack
