### ISSUE TITLE
Can you add support for Resource packs or texture packs?

### ISSUE THREAD

**Issue by BluEagle-Dev** [Just-Ju/Inmis-Back-Pack-Mod-Retextured#2]
Or if you can already do that for the mod, can you provide a template? To add custom models, using a resourcepack? That would make my day, thank you for your attention

**Comment by Just-Ju** [comment]
https://github.com/Just-Ju/Inmis-Back-Pack-Mod-Retextured/tree/Raw-files
I have already provided this you can download the raw files and within them you will see the model files and textures follow the instructions in the read me to add it directly to the mod :)
