### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by MysticcX** [Just-Ju/Inmis-Back-Pack-Mod-Retextured#3]
So I know there is another version of this addon: [InmisAddon](https://www.curseforge.com/minecraft/mc-mods/inmisaddon) however I prefer this over the other due to that fact that the textures look better and you don't need to install to mods for it to work. Would love to see this updated when needed, keep up the good work!

**Comment by Just-Ju** [comment]
Hey thank you for the reminder, I dont use this mod anymore to I kinda forget about it then theres a update 🙈 im glad you like the textures 😄❤️

**Comment by MysticcX** [comment]
Should upload this to Curseforge whenever you have free time to make it more accessible but yeah of course no problem!

**Comment by Just-Ju** [comment]
I didnt want to make it a curse forge page just out of respect of the original developer but I think your right i could props add it now.
