### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by Rogenar** [Just-Ju/Inmis-Back-Pack-Mod-Retextured#4]
inmis_retextured-2.7.0-1.19.jar version causes game to crash before starting.

**Comment by Just-Ju** [comment]
Can you post a crash report ?

**Comment by Rogenar** [comment]
[rei.log](https://github.com/Just-Ju/Inmis-Back-Pack-Mod-Retextured/files/10466116/rei.log)
[latest.log](https://github.com/Just-Ju/Inmis-Back-Pack-Mod-Retextured/files/10466118/latest.log)
[rei-issues.log](https://github.com/Just-Ju/Inmis-Back-Pack-Mod-Retextured/files/10466119/rei-issues.log)

**Comment by Just-Ju** [comment]
i see i will look into the issue in due course
